### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-evalopezm#1]
Buen trabajo @evalopezm !

### Algunas pistas para acabarlo:

- [x] Usa el estado de App.js para guardar los datos.
- [x] En App.js usa los datos guardados en el estado para pasárselos al componente PokeList.
- [x] Elimina el código comentado, debuggers y consoles
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Aquí la key no es necesaria https://github.com/Adalab/modulo-3-evaluacion-intermedia-evalopezm/blob/master/src/components/Pokemon.js#L11

### Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by evalopezm** [comment]
Cambios hechos y subidos, muchas gracias.
